version: 2

references:
node_image: &node_image node:10

working_directory: &working_directory ~/project

node_config: &node_config
  docker:
    - image: *node_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

jobs:
  before_script:
    <<: *node_config
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: Install Dependencies
          command: npm ci
      - *save_repo

  test:
    <<: *node_config
    steps:
      - *restore_repo
      - attach_workspace:
          at: *working_directory
      - run:
          name: Test
          command: npm test

  maybe_release:
    <<: *node_config
    steps:
      - *restore_repo
      - attach_workspace:
          at: *working_directory
      - run:
          name: Release if code changed
          command: bash .circleci/commit_check.sh

workflows:
  version: 2
  build-test-release:
    jobs:
      - before_script
      - test:
          requires:
            - before_script
      - maybe_release:
          requires:
            - test
          filters:
            branches:
              only: master
